### ISSUE TITLE
Remove PartialResponse and use ResponseBuilder to effectively clone Response

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-rest-client#10]

**Comment by sberyozkin** [comment]
Will try to do a PR

**Comment by sberyozkin** [comment]
It nearly worked, but we'd need to wait and see if the RestEasy team agrees to fix

https://issues.jboss.org/browse/RESTEASY-1991

**Comment by kenfinnigan** [comment]
Closing as implementation has been moved to https://github.com/resteasy/Resteasy/tree/master/resteasy-client-microprofile
