### ISSUE TITLE
Builder defaults to MediaType.TEXT_PLAIN

### ISSUE THREAD

**Issue by dvddhln** [smallrye/smallrye-rest-client#13]
https://github.com/smallrye/smallrye-rest-client/blob/c81b0529d7dff0fac780296614989d65749b98d0/implementation/src/main/java/io/smallrye/restclient/RestClientBuilderImpl.java#L136

The builder defaults to MediaType.TEXT_PLAIN for consumes and produces. Now if you want the accept header to be `"Accept: */*"` you have to add a `@Produces` annotation. Like this in the interface.

```
    @POST
    @Path("/operation")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces
    Response operation(String request);
```

Would it not make more sense to default the produces to `MediaType.WILDCARD` ?
Just a suggestion :)

**Comment by kenfinnigan** [comment]
We'd welcome a PR that fixes the issue

**Comment by dvddhln** [comment]
Here it is :)
https://github.com/smallrye/smallrye-rest-client/pull/14
