### ISSUE TITLE
Set bootstrap configuration connection settings on client ?

### ISSUE THREAD

**Issue by dvddhln** [smallrye/smallrye-rest-client#15]
Currently one can set the pool connection properties through the rest client builder

`RestClientBuilder.newBuilder().baseUrl(url).property("resteasy.connectionPoolSize", poolSize).build(HelloClient.class);`

Is there anyway to set these properties on the client without going through the builder but just through using annotations? I'm imagining it could be done through YAML configuration but glancing at the `RestClientBuilderImpl` it doesn't seem possible at the moment.

**Comment by kenfinnigan** [comment]
I don't believe JAX-RS has any annotations for those type of properties, and the MP REST Client spec hasn't introduced any.

Support for setting it through configuration could be added

**Comment by kenfinnigan** [comment]
Merged
