### ISSUE TITLE
Re-evaluate property naming

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-rest-client#17]
With #16 we introduced the ability to configure other properties on the Client connection.

Worth investigating if there's a better/alternative naming strategy for it

**Comment by dvddhln** [comment]
Perhaps its better to assume that any property set on the bootstrap is picked up as a property and added to the builder rather than having explicit prefix path 'property'.

**Comment by kenfinnigan** [comment]
Closing as implementation has been moved to https://github.com/resteasy/Resteasy/tree/master/resteasy-client-microprofile
