### ISSUE TITLE
ExceptionMapping#filter() may throw ClassCastException

### ISSUE THREAD

**Issue by mkouba** [smallrye/smallrye-rest-client#36]
I'm not quite sure this cast is legal:
https://github.com/smallrye/smallrye-rest-client/blob/master/implementation/src/main/java/io/smallrye/restclient/ExceptionMapping.java#L77

Unfortunately, the history is lost and I have no idea why it was implemented this way.

@michalszynkiewicz WDYT?

**Comment by michalszynkiewicz** [comment]
Doesn't look good indeed. I think checking if it's an `instanceof WebApplicationException` and wrapping it into one if it's not would be better.
