### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-rest-client#56]
#44 introduced impl of MP Rest Client 1.2. Please close this once 1.2 smallrye is released.

**Comment by kenfinnigan** [comment]
I'm currently working out some integration issues before doing a release

**Comment by kenfinnigan** [comment]
1.2.0 has now been released and should be available in the next few hours

**Comment by pavolloffay** [comment]
thanks @kenfinnigan I will go forward and release MP-OT 1.2
