### ISSUE TITLE
Update to MP REST Client 1.1

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-rest-client#6]
Update to MP REST Client 1.1 in implementation

**Comment by mkouba** [comment]
So it seems that 1.1 also introduces [Asynchronous Support](https://github.com/eclipse/microprofile-rest-client/blob/master/spec/src/main/asciidoc/async.asciidoc) but it's completely missing in release notes :-(, see also https://github.com/eclipse/microprofile-rest-client/issues/118.

@kenfinnigan This means we would have to merge https://github.com/smallrye/smallrye-rest-client/pull/9 first. RESTEasy 3.0 does not support `CompletionStage` return types.

**Comment by kenfinnigan** [comment]
@mkouba, do you know if RESTEasy 3.6 is still Java EE 7?

One issue would be whether updating would even work in Thorntail, ie. whether we can do that with modules, etc

**Comment by asoldano** [comment]
RESTEasy 3.6 series is JAX-RS 2.1 compliant (it's included in latest WildFly which is EE8 certified). This said, 3.6 is fully backward compatible with 3.0

**Comment by asoldano** [comment]
4.x is meant for bringing the new features that can't be implemented in a fully backward compatible ways as well as to allow some long waited refactoring / cleanup.

**Comment by kenfinnigan** [comment]
Thanks! One last thing @asoldano, would you see it as possible to integrate RESTEasy 3.6 into WildFly 11? I ask as that's what Thorntail 2.x currently has as the base WildFly

**Comment by asoldano** [comment]
https://github.com/resteasy/Resteasy/blob/3.6.1.Final/.travis.yml#L11 ... so yes

**Comment by pavolloffay** [comment]
Any update on this? When is it going to be implemented?

**Comment by kenfinnigan** [comment]
Possibly not for a bit, we need to discuss the best approach, which might mean switching to MP 2.x series and skipping 1.4
