### ISSUE TITLE
can't use RestClient in a standalone way (outside of a runtime)

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-rest-client#70]
In the Thorntail context, I see people often trying to use MP RestClient in a test, that is, in a standalone way, outside of the application. Obviously we don't support that, even though the spec says "MicroProfile Rest Client can be used as a standalone technology".

Here are the cases I've seen:
- https://github.com/javaee-samples/microprofile1.4-samples/blob/master/rest-client/client-server/src/test/java/org/eclipse/microprofile14/restclient/clientserver/ClientServerTest.java
- https://github.com/smallrye/smallrye-opentracing/issues/57
- https://issues.jboss.org/browse/THORN-2382

Either we should support that, or we should get the spec to change.

**Comment by kenfinnigan** [comment]
Closing as implementation has been moved to https://github.com/resteasy/Resteasy/tree/master/resteasy-client-microprofile
