### ISSUE TITLE
Have RestClientProxy extend AutoCloseable

### ISSUE THREAD

**Issue by bstansberry** [smallrye/smallrye-rest-client#79]
If RestClientProxy extended java.lang.AutoCloseable callers could use try-with-resources and could use the client close feature without needing a compile-time dep on smallryte-rest-client.

Of course users who did that would need to deal with the fact that AutoCloseable.close() throws Exception. The subinterface doesn't have to declare that though, so existing callers or ones not wanting to deal with that can cast to the subinterface.

**Comment by Ladicek** [comment]
Ability to close the client will actually become a portable feature in MP RestClient 1.3: https://github.com/eclipse/microprofile-rest-client/releases/tag/1.3-RC1

**Comment by bstansberry** [comment]
Cool; I'll close this then as that covers the need.
