### ISSUE TITLE
Correct usage of http.nonProxyHosts system property

### ISSUE THREAD

**Issue by aax** [smallrye/smallrye-rest-client#82]
The current implementation in io.smallrye.restclient.RestClientBuilderImpl does not correctly use the http.nonProxyHosts system property. It does not parse it like usual implementations do (see https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html), even if it suggests it by having the default value "localhost|127.*|[::1]".

This is the line of Code that causes the problem: https://github.com/smallrye/smallrye-rest-client/blob/737876ec42853eb966d29228334c7c91f04128ed/implementation/src/main/java/io/smallrye/restclient/RestClientBuilderImpl.java#L158

I suggest using the ProxySelector to read the standard system properties for proxy configuration and resolving the nonProxyHosts. I could provide a PR with this change if welcomed.

**Comment by kenfinnigan** [comment]
We'd love a PR! Thanks
